repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: ebb7352ea67ebad30aa5ad6ba5da246a218f3b21
    hooks:
      - id: gearcheck
        always_run: true
      - id: poetry_export
      - id: docker_build
      - id: yamllint
      - id: ruff
        args: [
          "--config", "pyproject.toml",
          --ignore, "E501",
          --fix,
        ]
      - id: ruff_tests
      - id: pytest
