repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: dee3cd63f9f4d7a2ab95b41f01281b97fd480cf7
    hooks:
      - id: poetry_export
      - id: gearcheck
      - id: hadolint
      - id: jsonlint
      - id: linkcheck
      - id: markdownlint
      - id: yamllint
      - id: ruff
      - id: ruff_format
      - id: ruff_tests
