repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: 053a9ee08d967147f9a69fc32a7f3acdfded78df
    hooks:
      - id: gearcheck
        always_run: true
      - id: poetry_export
      - id: docker_build
      - id: yamllint
      - id: ruff
        args: [
          "--config", "pyproject.toml",
          --ignore, "E501",
          --fix,
        ]
      - id: ruff_tests
      - id: pytest
