repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: f47f107929809c56e423685a85194fce5124c385
    hooks:
      - id: gearcheck
        always_run: true
      - id: poetry_export
      - id: docker_build
      - id: yamllint
      - id: ruff
        args: [
          "--config", "pyproject.toml",
          --ignore, "E501",
          --fix,
        ]
      - id: ruff_tests
      - id: pytest
