repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: 3da2396b007bb4ec3a8d27c0a0724209b0a607cf
    hooks:
      - id: gearcheck
        always_run: true
      - id: poetry_export
      - id: docker_build
      - id: yamllint
      - id: ruff
        args: [
          "--config", "pyproject.toml",
          --ignore, "E501",
        ]
      - id: ruff_format
      - id: ruff_tests
      - id: pytest
