repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: 370fbfea2174dff02f4a2d8c48e52b1e7d7e5cb3
    hooks:
      - id: pyproject_export
      - id: gearcheck
      - id: eolfix
      - id: hadolint  # Dockerfile linter (recommended)
      - id: jsonlint
      - id: linkcheck
      - id: markdownlint
      - id: yamllint
      - id: ruff_format
      - id: ruff
        args: ["--config", "pyproject.toml"]
      - id: ruff_tests
      - id: pytest
